/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOlympusZap, IOlympusZapInterface } from "../IOlympusZap";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "principal",
        type: "address",
      },
      {
        internalType: "address",
        name: "depository",
        type: "address",
      },
    ],
    name: "update_BondDepository",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IStaking",
        name: "_staking",
        type: "address",
      },
    ],
    name: "update_Staking",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_sOHM",
        type: "address",
      },
    ],
    name: "update_sOHM",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wsOHM",
        type: "address",
      },
    ],
    name: "update_wsOHM",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOlympusZap__factory {
  static readonly abi = _abi;
  static createInterface(): IOlympusZapInterface {
    return new utils.Interface(_abi) as IOlympusZapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOlympusZap {
    return new Contract(address, _abi, signerOrProvider) as IOlympusZap;
  }
}
